### ISSUE TITLE
Enhanced Documentation

### ISSUE THREAD

**Issue by Paultagoras** [ClickHouse/clickhouse-kafka-connect#236]
Add documentation on the company website:

- [X] Tuning `consumer` setting to optimize the ClickHouse insert
- [X] Recommended `consumer` setting 
- Step-by-step setup guides
- [ ]   On-Prem
- [ ]   Confluent Cloud
- [ ]   MSK
- [ ]   RedPanda
- Architecture
- [x]   - Overview
- [x]   - Exactly Once Implementation
- Provide CONTRIBUTING doc:
- [x] - Requirements for the dev environment
- [x] - How to run tests

```[tasklist]
### Tasks
```

**Comment by mshustov** [comment]
`tableRefreshInterval` setting is not documented
